// Generated by gencpp from file astarfun/path_ok.msg
// DO NOT EDIT!


#ifndef ASTARFUN_MESSAGE_PATH_OK_H
#define ASTARFUN_MESSAGE_PATH_OK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace astarfun
{
template <class ContainerAllocator>
struct path_ok_
{
  typedef path_ok_<ContainerAllocator> Type;

  path_ok_()
    : path_ok(false)  {
    }
  path_ok_(const ContainerAllocator& _alloc)
    : path_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _path_ok_type;
  _path_ok_type path_ok;





  typedef boost::shared_ptr< ::astarfun::path_ok_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::astarfun::path_ok_<ContainerAllocator> const> ConstPtr;

}; // struct path_ok_

typedef ::astarfun::path_ok_<std::allocator<void> > path_ok;

typedef boost::shared_ptr< ::astarfun::path_ok > path_okPtr;
typedef boost::shared_ptr< ::astarfun::path_ok const> path_okConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::astarfun::path_ok_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::astarfun::path_ok_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::astarfun::path_ok_<ContainerAllocator1> & lhs, const ::astarfun::path_ok_<ContainerAllocator2> & rhs)
{
  return lhs.path_ok == rhs.path_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::astarfun::path_ok_<ContainerAllocator1> & lhs, const ::astarfun::path_ok_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace astarfun

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::astarfun::path_ok_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::astarfun::path_ok_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::astarfun::path_ok_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::astarfun::path_ok_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::astarfun::path_ok_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::astarfun::path_ok_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::astarfun::path_ok_<ContainerAllocator> >
{
  static const char* value()
  {
    return "276f6ed1d160276c34d8bfda3a611a63";
  }

  static const char* value(const ::astarfun::path_ok_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x276f6ed1d160276cULL;
  static const uint64_t static_value2 = 0x34d8bfda3a611a63ULL;
};

template<class ContainerAllocator>
struct DataType< ::astarfun::path_ok_<ContainerAllocator> >
{
  static const char* value()
  {
    return "astarfun/path_ok";
  }

  static const char* value(const ::astarfun::path_ok_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::astarfun::path_ok_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool path_ok\n"
;
  }

  static const char* value(const ::astarfun::path_ok_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::astarfun::path_ok_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_ok_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::astarfun::path_ok_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::astarfun::path_ok_<ContainerAllocator>& v)
  {
    s << indent << "path_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.path_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASTARFUN_MESSAGE_PATH_OK_H
