<robot name="my_car_move" xmlns:xacro="http://wiki.ros.org/xacro">


    <xacro:macro name="joint_trans" params="joint_name">
        <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${joint_name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint_name}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

  
    <xacro:joint_trans joint_name="front_left_wheel2base" />
    <xacro:joint_trans joint_name="front_right_wheel2base" />
    <xacro:joint_trans joint_name="rear_left_wheel2base" />
    <xacro:joint_trans joint_name="rear_right_wheel2base" />

  
    <gazebo>
        <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>true</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>200.0</updateRate>
            <legacyMode>false</legacyMode>
            <leftFrontJoint>front_left_wheel2base</leftFrontJoint>
            <rightFrontJoint>front_right_wheel2base</rightFrontJoint>
            <leftRearJoint>rear_left_wheel2base</leftRearJoint>
            <rightRearJoint>rear_right_wheel2base</rightRearJoint>
            <wheelSeparation>${wheel2base_y * 2}</wheelSeparation> 
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter> 
            <broadcastTF>1</broadcastTF>
            <torque>20</torque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic> 
            <odometryFrame>odom</odometryFrame> 
            <odometryTopic>odom</odometryTopic> 
            <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
    </gazebo>

  <gazebo reference="rear_right_wheel">
        <material>Gazebo/Black</material>
        <mu1>10000000</mu1>
        <mu2>10000000</mu2>
        <kp>10000000</kp>
        <kd>1</kd>
    </gazebo>
    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Black</material>
        <mu1>10000000</mu1>
        <mu2>10000000</mu2>
        <kp>10000000</kp>
        <kd>1</kd>
    </gazebo>
    <gazebo reference="front_left_wheel">
        <material>Gazebo/Black</material>
        <mu1>10000000</mu1>
        <mu2>10000000</mu2>
        <kp>10000000</kp>
        <kd>1</kd>
    </gazebo>
    <gazebo reference="front_right_wheel">
        <material>Gazebo/Black</material>
        <mu1>10000000</mu1>
        <mu2>10000000</mu2>
        <kp>10000000</kp>
        <kd>1</kd>
    </gazebo>
</robot>
